---
- include_vars: "{{ ansible_os_family }}.yml"
#  with_first_found:
#    - "{{ ansible_distribution }}.yml"
#    - "{{ ansible_os_family }}.yml"
#    - "default.yml"
- include: packages.yml
- include: user.yml
- include: configs.yml
- include: openstack.yml
